/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'clothing' : null } |
  { 'food' : null } |
  { 'books' : null } |
  { 'electronics' : null };
export type DeliveryType = { 'oneHourDelivery' : null } |
  { 'takeaway' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'total' : bigint,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'productId' : ProductId, 'quantity' : bigint }
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : ProductId,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'deliveryType' : DeliveryType,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export type ProductId = bigint;
export interface ShoppingCart { 'total' : bigint, 'items' : Array<OrderItem> }
export interface UserOrderHistory { 'orders' : Array<Order> }
export interface UserProfile { 'name' : string, 'phoneNumber' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[], undefined>,
  'createProduct' : ActorMethod<
    [string, string, bigint, Category, string, bigint, DeliveryType],
    Product
  >,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], ShoppingCart>,
  'getOrderHistory' : ActorMethod<[], UserOrderHistory>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartQuantity' : ActorMethod<[ProductId, bigint], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, bigint, Category, string, bigint, DeliveryType],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];